name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  deploy-bin-windows-i686:
    needs: check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: i686-pc-windows-msvc
          toolchain: stable
      - name: Build divvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin divvunspell --release --target i686-pc-windows-msvc
  deploy-bin-windows-x86_64:
    needs: check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-pc-windows-msvc
          toolchain: stable
      - name: Build divvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin divvunspell --release --target x86_64-pc-windows-msvc
  deploy-bin-macos-arm64:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: aarch64-apple-darwin
          toolchain: stable
      - name: Build divvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin divvunspell --release --target aarch64-apple-darwin
  deploy-bin-macos-x86_64:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-apple-darwin
          toolchain: stable
      - name: Build divvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin divvunspell --release --target x86_64-apple-darwin
  deploy-lib-ios-aarch64:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: aarch64-apple-ios
          toolchain: stable
      - name: Build libdivvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --release --features internal_ffi --target aarch64-apple-ios
  deploy-lib-ios-x86_64:
    needs: check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-apple-ios
          toolchain: stable
      - name: Build libdivvunspell
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --release --features internal_ffi --target x86_64-apple-ios
